server:
  port: ${PORT:8080}

eureka:
  instance:
    prefer-ip-address: true
    hostname: /api
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka:8761/eureka}
    register-with-eureka: true
    fetch-registry: true

spring:
  application:
    name: zuul-gateway