server:
  port: ${PORT:8080}

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
spring:
  application:
    name: zuul-gateway
  profiles:
    active: development

zuul:
  prefix: /api
  host:
    socket-timeout-millis: 30000
  routes:
    customer-service:
      serviceId: customer
    store-service:
      serviceId: store
    order-service:
      serviceId: order