spring:
  application:
    name: store
  profiles:
    active: development

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1

ribbon:
  eureka:
    enabled: false